/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as MainLayoutIndexRouteImport } from './routes/_mainLayout/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as MainLayoutCollectionRouteImport } from './routes/_mainLayout/collection'
import { Route as AuthLayoutSignUpRouteImport } from './routes/_authLayout/sign-up'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as AuthLayoutEmailVerificationRouteImport } from './routes/_authLayout/email-verification'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutCollectionRoute = MainLayoutCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLayoutSignUpRoute = AuthLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutEmailVerificationRoute =
  AuthLayoutEmailVerificationRouteImport.update({
    id: '/email-verification',
    path: '/email-verification',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/email-verification': typeof AuthLayoutEmailVerificationRoute
  '/login': typeof AuthLayoutLoginRoute
  '/sign-up': typeof AuthLayoutSignUpRoute
  '/collection': typeof MainLayoutCollectionRoute
  '/demo/table': typeof DemoTableRoute
}
export interface FileRoutesByTo {
  '/': typeof MainLayoutIndexRoute
  '/email-verification': typeof AuthLayoutEmailVerificationRoute
  '/login': typeof AuthLayoutLoginRoute
  '/sign-up': typeof AuthLayoutSignUpRoute
  '/collection': typeof MainLayoutCollectionRoute
  '/demo/table': typeof DemoTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_authLayout/email-verification': typeof AuthLayoutEmailVerificationRoute
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/sign-up': typeof AuthLayoutSignUpRoute
  '/_mainLayout/collection': typeof MainLayoutCollectionRoute
  '/demo/table': typeof DemoTableRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-verification'
    | '/login'
    | '/sign-up'
    | '/collection'
    | '/demo/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-verification'
    | '/login'
    | '/sign-up'
    | '/collection'
    | '/demo/table'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_mainLayout'
    | '/_authLayout/email-verification'
    | '/_authLayout/login'
    | '/_authLayout/sign-up'
    | '/_mainLayout/collection'
    | '/demo/table'
    | '/_mainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/collection': {
      id: '/_mainLayout/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof MainLayoutCollectionRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_authLayout/sign-up': {
      id: '/_authLayout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthLayoutSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/email-verification': {
      id: '/_authLayout/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof AuthLayoutEmailVerificationRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutEmailVerificationRoute: typeof AuthLayoutEmailVerificationRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutSignUpRoute: typeof AuthLayoutSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutEmailVerificationRoute: AuthLayoutEmailVerificationRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutSignUpRoute: AuthLayoutSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface MainLayoutRouteChildren {
  MainLayoutCollectionRoute: typeof MainLayoutCollectionRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutCollectionRoute: MainLayoutCollectionRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  MainLayoutRoute: MainLayoutRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
